version: '3.1'

services:
  neo4j:
    container_name: sooljari-neo4j
    image: neo4j:5.12.0
    user: ${USER_ID}:${GROUP_ID}
    ports:
      - 7474:7474
      - 7687:7687
    env_file: .env
    volumes:
      - ./.data:/data
      - ./.conf:/conf
      - ./.logs:/logs
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    networks:
      - backend

networks:
  backend:
    external: true
